//
//  parkList.swift
//  PowerPlay
//
//  Created by Aadit Noronha on 7/17/23.
//

import Foundation

struct parkList {
    var names = ["25th Street Mini Park", "85th Avenue Mini Park", "88th Avenue Mini Park", "Allendale Park", "Arroyo Viejo Park", "Avenue Terrace Park", "Ayala Park", "Beaconsfield Canyon", "Bella Vista Park", "Bertha Port Park", "Bishop Floyd L. Begin Plaza", "Brookdale Park", "Burckhalter Park", "Bushrod Park", "Caldecott Field / North Oakland Regional Sports Center", "Carney Park", "Carter-Gilmore/Greenman Field", "Central Reservoir Park", "Cesar Chavez Park", "Chabot Park", "Channel Park", "Chinese Garden Park", "Cleveland Cascade (Brooklyn Plaza)", "Clinton Square Park", "Colby Park", "Coliseum Gardens Park", "Columbian Gardens Park", "Concordia Park", "Cresent Park", "Cypress Freeway Memorial Park", "DeFremery Park", "Dimond Park/Canyon", "Dolphin Mini Park", "Dover Street Park", "Driver [Jasper P.] Plaza", "Dunsmuir Estate Park", "Durant Mini Park", "Eastshore Park (Astro Play Area)", "Elmhurst Lyons Field", "Estuary Channel Park", "Firestorm Memorial Garden", "Fitzgerald Park", "FM Smith Park", "Foothill Meadows Extension", "Foothill Meadows Extension", "Frank Ogawa Firescape Garden", "Franklin Park", "Franklin Plaza", "Fruitvale Bridge Park", "Garber [John] Park", "Garfield Park", "Gateway Gardens Park & Pavillion", "Glen Echo Park", "Golden Gate Park", "Grove Shafter Park & Dog Park", "Hardy Park & Dog Park", "Helen McGregor Plaza Park", "Henery J. Kaiser Memorial Park (Remember Them: Champions For Humanity Monument)", "Holly Mini Park", "Jefferson Square / Dog Park", "Joaquin Miller Park / Dog Park", "Josie de la Cruz Park", "King Estates Park (Glenn Daniel)", "Knowland Park", "Lafayette Square Park", "Lakeside Park", "Lazear Park", "Leona Heights Park", "Lincoln Square Park", "Linden Park", "Lowell Park", "Mandana Plaza Park", "Manzanita Park", "Marj Saunders Park", "Marston Campbell Park", "Maxwell Park", "McClymonds Mini Park", "McCrea Park", "Montclair Park", "Montclair Railroad Trail", "Morcom Rose Garden", "Morgan Plaza Park", "Mosswood Park & Dog Park", "Nicol Park", "Oak Glen Park", "Officer Willie Wilkins Park", "Ostrander Park", "Park Blvd Plaza Park", "Peralta Hacienda Park", "Peralta Oaks Park", "Peralta Park", "Piedmont Plaza Park", "Pine Knoll Park", "Pinto Park", "Poplar Park", "Raimondi Park", "Rainbow Park", "Rancho Peralta Park", "Redondo Park", "Redwood Heights Park", "Rockridge Park", "Rockridge-Temescal Greenbelt (FROG Park)", "Saint Andrews Plaza", "San Antonio Park", "Sequoia Lodge Park", "Sheffield Village Park", "Shepherd Canyon Park", "Snow Park", "Sobrante Park", "South Prescott Park", "Splash Pad Park", "Stonehurst Park", "Tassafaronga Park", "Temescal Creek Park", "Tomas Melero-Smith", "Tyrone Carney Park", "Union Plaza", "Union Point Park", "Vantage Point Park", "Verdese Carter Park", "Wade Johnson Park", "William \"Bill\" Patterson Park", "William Wood Park", "Willow Mini Park", "Willow Mini Park", "Wilma Chan Park", "Wood Park", "Wood Street Pocket Park"]
}

